" Use Vim settings, rather then Vi settings
" This must be first, because it changes other options as a side effect
set nocompatible

" ------------------------------------------------------------------------------
" General Config
" ------------------------------------------------------------------------------
set number                     " Line numbers
set relativenumber             " Relative numbering
set backspace=indent,eol,start " Allow backspace in insert mode
set history=1000               " Store lots of :cmdline history
set showcmd                    " Show incomplete cmds down the bottom
set showmode                   " Show current mode down the bottom
set visualbell                 " No sounds
set autoread                   " Reload files changed outside vim
set hidden                     " Allow buffers to exist in background
set noswapfile                 " No swap file
set nobackup                   " No backup
set nowb                       " No write-backup
set laststatus=2               " Always show statusline
set foldmethod=syntax          " Enable syntax folding
set foldlevelstart=20          " Set starting fold high so file starts unfolded
set t_Co=16                    " Set terminal color to 16
set colorcolumn=80             " Highlight column 80
set cursorline                 " Highlight current line
syntax on                      " Turn on syntax
syntax enable                  " Enable syntax

" ------------------------------------------------------------------------------
"  Set ESC and Leader
" ------------------------------------------------------------------------------
imap jj <Esc>
let mapleader = ' '

" ------------------------------------------------------------------------------
" Move normally between wrapped lines
" ------------------------------------------------------------------------------
nmap j gj
nmap k gk

" ------------------------------------------------------------------------------
" Indentation and Linebreaks
" ------------------------------------------------------------------------------
set autoindent
set smartindent
set smarttab
set shiftwidth=2
set softtabstop=2
set tabstop=2
set expandtab
set nowrap
set linebreak

" ------------------------------------------------------------------------------
" Search Config
" ------------------------------------------------------------------------------
set hlsearch
set incsearch
set ignorecase
set smartcase

" ------------------------------------------------------------------------------
" Automatically save file
" ------------------------------------------------------------------------------
autocmd FocusLost * silent! wa

" ------------------------------------------------------------------------------
" Persistent Undo -- Keep undo history across sessions by storing in file
" ------------------------------------------------------------------------------
if has('persistent_undo')
  silent !mkdir ~/.vim/backups > /dev/null 2>&1
  set undodir=~/.vim/backups
  set undofile
endif

" ------------------------------------------------------------------------------
" Airline Config
" ------------------------------------------------------------------------------
let g:airline#extensions#tabline#enabled = 1
let g:airline_powerline_fonts = 1

" ------------------------------------------------------------------------------
" TComment Config
" ------------------------------------------------------------------------------
let g:tcommentMaps=0                          " Disable keymappings
nmap gcc :TComment<CR>                        " Comment visual block
vmap gc :TComment<CR>                         " Comment visual block

" ------------------------------------------------------------------------------
" GitGutter Config
" ------------------------------------------------------------------------------
let g:gitgutter_map_keys=0 " Disable keymappings

" ------------------------------------------------------------------------------
" CtrlP Config
" ------------------------------------------------------------------------------
let g:ctrlp_working_path_mode='a'

" ------------------------------------------------------------------------------
" YouCompleteMe Config
" ------------------------------------------------------------------------------
let g:ycm_server_keep_logfiles = 1
let g:ycm_server_log_level = 'debug'
if has('win32')
  let ycm_path_to_python_interpreter = 'C:\Python35\python.exe'
end

" ------------------------------------------------------------------------------
" OmniSharp Config
" ------------------------------------------------------------------------------
" let g:OmniSharp_server_type = 'roslyn'

" ------------------------------------------------------------------------------
" Notes Config
" ------------------------------------------------------------------------------
let g:notes_directories = ['~/Dropbox/vim-notes']

" ------------------------------------------------------------------------------
" Bookmarks Config
" ------------------------------------------------------------------------------
let g:bookmark_no_default_key_mappings = 1

" ------------------------------------------------------------------------------
" Space Based Keybindings
" ------------------------------------------------------------------------------

" Bookmarks
nnoremap <leader>Bb :BookmarkToggle<CR>            " Toggle on current line
nnoremap <leader>Bn :BookmarkNext<CR>              " Next
nnoremap <leader>Bp :BookmarkPrev<CR>              " Previous
nnoremap <leader>Ba :BookmarkShowAll<CR>           " Show All
nnoremap <leader>Bc :BookmarkClear<CR>             " Clear in current buffer

" Buffer
nnoremap <leader><Tab> :e#<CR>                     " Switch to last buffer
nnoremap <leader>bb :CtrlPBuffer<CR>               " List
nnoremap <leader>bn :bnext<CR>                     " Next
nnoremap <leader>bp :bprevious<CR>                 " Previous
nnoremap <leader>bd :bdelete<CR>                   " Delete

" Folding
nnoremap <leader>ff za                             " Toggle current fold
nnoremap <leader>fo zR                             " Open all folds
nnoremap <leader>fc zM                             " Close all folds
nnoremap <leader>fv zv                             " View cursor line

" Git
nnoremap <leader>gdn :GitGutterNextHunk<CR>        " Jump to next diff
nnoremap <leader>gdp :GitGutterPrevHunk<CR>        " Jump to previous diff
nnoremap <leader>gdt :GitGutterToggle<CR>          " Toggle git-gutter

" Linting (Errors)
nnoremap <leader>ec :SyntasticCheck<CR>            " Error check
nnoremap <leader>ee :Errors<CR>                    " List errors
nnoremap <leader>et :SyntasticToggleMode<CR>       " Toggle syntastic

" Meta
nnoremap <leader>_d :e $MYVIMRC<CR>                " Edit .vimrc
nnoremap <leader>_r :source $MYVIMRC<CR>           " Reload .vimrc
nnoremap <leader>_p : ~/.vim/work/projects.vim<CR> " Edit work projects file

" Project
nnoremap <leader>pt :FileBeagle<CR>                " Opens cwd
nnoremap <leader>pF :FileBeagleBufferDir<CR>       " Opens directory of current file
nnoremap <leader>pf :CtrlP<CR>                     " Fuzzy-search through files

" Window splits
nnoremap <leader>wv <C-w>v<C-w>l                   " Split vertically
nnoremap <leader>wh <C-w>s<C-w>j                   " Split horizontally

" Window navigation
nnoremap <leader>h <C-w>h<CR>                      " Navigate left
nnoremap <leader>j <C-w>j<CR>                      " Navigate down
nnoremap <leader>k <C-w>k<CR>                      " Navigate up
nnoremap <leader>l <C-w>l<CR>                      " Navigate right

" ------------------------------------------------------------------------------
" ConEmu Config
" ------------------------------------------------------------------------------
if !empty($CONEMUBUILD)
    set term=xterm
    set termencoding=utf8
    set t_Co=16
    let &t_AB="\e[48;5;%dm"
    let &t_AF="\e[38;5;%dm"
endif

" ------------------------------------------------------------------------------
" Vundle Config
" ------------------------------------------------------------------------------
filetype off

" Install Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Let Vundle manage Vundle, required
Bundle 'gmarik/Vundle.vim'

" Editor features
Bundle 'tpope/vim-surround'
Bundle 'jiangmiao/auto-pairs'
Bundle 'tomtom/tcomment_vim.git'

" File browsing
Bundle 'jeetsukumaran/vim-filebeagle'
Bundle 'ctrlpvim/ctrlp.vim'

" Formatting
Bundle 'ntpeters/vim-better-whitespace'
Bundle 'godlygeek/tabular'

" Linting
Bundle 'scrooloose/syntastic'

" Git
Bundle 'airblade/vim-gitgutter'

" Auto-Complete
Bundle 'Valloric/YouCompleteMe'

" CSharp
Bundle 'OmniSharp/omnisharp-vim'

" Python
Bundle 'Bogdanp/pyrepl.vim'

" Tools
Bundle 'xolox/vim-misc'
Bundle 'xolox/vim-notes'
Bundle 'MattesGroeger/vim-bookmarks'
Bundle 'tpope/vim-dispatch'
Bundle 'junegunn/vader.vim'
Bundle 'amiorin/vim-project'

" Syntax
Bundle 'OrangeT/vim-csharp'

" Visuals
Bundle 'bling/vim-airline'
Bundle 'vim-airline/vim-airline-themes'
Bundle 'altercation/vim-colors-solarized'

call vundle#end()            " Required
filetype plugin indent on    " Required

" ------------------------------------------------------------------------------
" Solarized Theme (Must be set after Vundle)
" ------------------------------------------------------------------------------
set background=dark
colorscheme solarized

" ------------------------------------------------------------------------------
" Project Config
" ------------------------------------------------------------------------------
set rtp+=~/.vim/bundle/vim-project/
call project#rc('/src')

Project 'dotfiles'
Project 'sublime-gherkin-auto-complete-plus'

" Get work projects if the file exists
if filereadable($HOME . "/.vim/work/projects.vim")
  source $HOME/.vim/work/projects.vim
end
