# colors
alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# ls
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

# clear screen
alias cls='clear'

# vim
alias vim-classic='/usr/bin/vim'
alias vim='nvim'

# dotnet
alias msbuild='xbuild'
alias fsc='fsharpc'
alias fsi='fsharpi'
